### ISSUE TITLE
Doors are bugged

### ISSUE THREAD

**Issue by rinart73** [ChloeDawn/Couplings#6]
Minecraft: 1.14.4
Fabric: 0.4.8 build 159
Mod version: 1.1.0

Sometimes only one door opens. Or only half of the door opens. Or door opens but you can't go through it because you get stuck.

**Comment by calloatti** [comment]
You are probably trying to open a door in a chunk claimed by another player.

See https://www.curseforge.com/minecraft/mc-mods/claimchunk

All the symptoms you describe match how that mod behaves.

**Comment by rinart73** [comment]
I don't have claimchunk installed.
My mods:
appleskin-mc1.14-fabric-1.0.7
fabric-api-0.3.1+build.208
foamfix-0.12.1
glassdoor-1.3.2
Hwyla-fabric-1.14.2-1.9.17-66
optifabric-0.5.1
OptiFine_1.14.4_HD_U_F3
RoughlyEnoughItems-2.9.8+build.150

**Comment by InsomniaKitten** [comment]
Does this happen with only Couplings installed? If not, try removing mods one by one until doors work again, then report back with your findings.
